name: Deploy Terraform

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::302263075199:role/OIDC-Terraform
          aws-region: us-west-2

      - name: List Directory Contents
        run: ls -la ./Infra

      - name: Install TFLint
        run: |
          TFLINT_VERSION="v0.55.0"
          curl -sL "https://github.com/terraform-linters/tflint/releases/download/${TFLINT_VERSION}/tflint_linux_amd64.zip" -o tflint.zip
          
          if [ ! -s "tflint.zip" ]; then
            echo "Error: Downloaded TFLint archive is empty or invalid."
            exit 1
          fi

          unzip tflint.zip
          chmod +x tflint
          sudo mv tflint /usr/local/bin/
          rm tflint.zip
          
          echo "TFLint installed successfully:"
          tflint --version

      - name: Install Checkov
        run: |
          pip install checkov
          checkov --version

      - name: Run Checkov Security Scan
        run: |
          cd Infra
           checkov --directory . --check CKV_AWS_118,CKV_AWS_119 --skip-check CKV_AWS_116 -v
          
      - name: Terraform Init
        run: terraform init
        working-directory: ./Infra

      - name: Terraform Apply
        run: terraform apply -var-file=terraform.tfvars -auto-approve
        working-directory: ./Infra
