name: Build and Push Docker Images to ECR

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Configure AWS credentials using OIDC
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::302263075199:role/OIDC-Terraform
        aws-region: us-east-1

    # Log in to Amazon ECR
    - name: Log in to Amazon ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 302263075199.dkr.ecr.us-east-1.amazonaws.com

    # Create ECR repository for Patient Service if it doesn't exist
    - name: Create ECR repository for Patient Service
      run: |
        aws ecr describe-repositories --repository-names hello_world --region us-east-1 || \
        aws ecr create-repository --repository-name hello_world --region us-east-1


    # Build, tag, and push Docker image for Patient Service
    - name: Build, Tag & Push Docker Image for Patient Service
      run: |
        cd App/hello_world/
        docker build -t hello_world:latest -f Dockerfile .
        docker tag hello_world:latest 302263075199.dkr.ecr.us-east-1.amazonaws.com/patient-service:latest
        docker push 302263075199.dkr.ecr.us-east-1.amazonaws.com/patient-service:latest
